name: linter
on: [push, pull_request]

jobs:
  repolinter:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: newrelic/repolinter-action@cd9cd19 #v1.6.0
